## Decision Analysis - Project 1

Authors:
* Szudzik Oskar, 148245
* Moras Krystian, 148243

In [9]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('apartments.csv',decimal=",")
df

link  price  \
0   https://www.otodom.pl//pl/oferta/2-niezalezne-...   2350   
1   https://www.otodom.pl//pl/oferta/2pokojowe-ata...   2300   
2   https://www.otodom.pl//pl/oferta/nowe-mieszkan...   2800   
3   https://www.otodom.pl//pl/oferta/mieszkanie-2-...   1700   
4   https://www.otodom.pl//pl/oferta/nowe-komforto...   2350   
5   https://www.otodom.pl//pl/oferta/centrum-przy-...   2500   
6   https://www.otodom.pl//pl/oferta/mieszkanie-la...   1900   
7   https://www.otodom.pl//pl/oferta/luksusowy-apa...   8000   
8   https://www.otodom.pl//pl/oferta/paryski-szyk-...   2500   
9   https://www.otodom.pl//pl/oferta/nowe-2-pokojo...   2350   
10  https://www.otodom.pl//pl/oferta/2-pokoje-podo...   2700   
11  https://www.otodom.pl/pl/oferta/klimatyczne-mi...   2400   
12  https://www.otodom.pl/pl/oferta/dwupokojowe-mi...   2500   
13  https://www.otodom.pl/pl/oferta/mieszkanie-brz...   2800   

                                             address  \
0   Poznań, Piątkowo, ul. Zygmunta Wojciechowskiego    
1        Poznań, Piątkowo, osiedle Stefana Batorego    
2                      Poznań, Grunwald, ul. Ptasia    
3                   Poznań, Naramowice, ul. Radłowa    
4                           Podolany, Poznań, Poznań   
5      Poznań, Centrum, ul. Franciszka Ratajczaka 21   
6                   Poznań, Łazarz, ul. Głogowska 65   
7        Poznań, Chwaliszewo, ul. Tylne Chwaliszewo    
8                 Poznań, Górna Wilda, ul. Różana 21   
9                  Poznań, Starołęka, ul. Wagrowska    
10                  Poznań, Podolany, ul. Jasielska    
11                           Poznań, Rzeczpospolitej   
12                                  Poznań, Piątkowo   
13                          Poznań, grunwald, brzask   

                                           directions  area  aesthetics  \
0   https://www.google.com/maps/dir/Centrum%20Wyk%...  40.0         7.0   
1   https://www.google.com/maps/dir/Centrum%20Wyk%...  50.0         3.0   
2   https://www.google.com/maps/dir/Centrum%20Wyk%...  49.0         6.0   
3   https://www.google.com/maps/dir/Centrum%20Wyk%...  32.5         5.0   
4   https://www.google.com/maps/dir/Centrum%20Wyk%...  43.0         7.5   
5   https://www.google.com/maps/dir/Centrum%20Wyk%...  45.0         7.0   
6   https://www.google.com/maps/dir/Centrum%20Wyk%...  48.0         2.0   
7   https://www.google.com/maps/dir/Centrum%20Wyk%...  78.0        10.0   
8   https://www.google.com/maps/dir/Centrum%20Wyk%...  54.0         6.0   
9   https://www.google.com/maps/dir/Centrum%20Wyk%...  41.0         8.0   
10  https://www.google.com/maps/dir/Centrum%20Wyk%...  50.0         6.0   
11  https://www.google.com/maps/dir/Centrum+Wykład...  50.0         5.0   
12  https://www.google.com/maps/dir/Centrum+Wyk%C5...  41.5         8.0   
13  https://www.google.com/maps/dir/Centrum+Wykład...  59.0         9.0   

    commutation  gym_num  
0            40        7  
1            42        6  
2            39        9  
3            44        2  
4            51        4  
5            19        3  
6            28        1  
7            17        2  
8            20        2  
9            23        1  
10           42       10  
11           14        3  
12           42        2  
13           38        7

Normalized data from google sheet: https://docs.google.com/spreadsheets/d/1VsbFXimgnc1h46ZDxTlhOrBB5JrDE3e36HZFIbUKY0M/edit?usp=sharing

In [138]:
alternatives = df[["price","area","aesthetics","commutation","gym_num"]]
alternatives

price  area  aesthetics  commutation  gym_num
0    2350  40.0         7.0           40        7
1    2300  50.0         3.0           42        6
2    2800  49.0         6.0           39        9
3    1700  32.5         5.0           44        2
4    2350  43.0         7.5           51        4
5    2500  45.0         7.0           19        3
6    1900  48.0         2.0           28        1
7    8000  78.0        10.0           17        2
8    2500  54.0         6.0           20        2
9    2350  41.0         8.0           23        1
10   2700  50.0         6.0           42       10
11   2400  50.0         5.0           14        3
12   2500  41.5         8.0           42        2
13   2800  59.0         9.0           38        7

In [140]:
def get_alternatives():
    df = pd.read_csv('apartments.csv',decimal=",")
    return df[["price","area","aesthetics","commutation","gym_num"]]

### PROMETHEE I

In [26]:
# TODO

### PROMETHEE II

In [28]:
# TODO

### ELECTRE

In [63]:
def concordance_function(difference,indifference,preference,gain):
    if gain:
        if difference >= -indifference:
            return 1
        elif difference < -preference:
            return 0
        else:
            return (preference + difference) / (preference-indifference)
    else:
        if difference <= indifference:
            return 1
        elif difference > preference:
            return 0
        else:
            return (preference-difference) / (preference-indifference)


def calculate_marginal_concordance(alternatives, boundary_profiles, indifference_thresholds, preference_thresholds, gain,concordance_function=concordance_function):
    # Calculate marginal concordance for each alternative and boundary profile
    # Arguments:
    #   alternatives: pandas dataframe with alternatives
    #   boundary_profiles: pandas dataframe with boundary profiles
    #   indifference_thresholds: list of indifference thresholds for each boundary profile
    #   preference_thresholds: list of preference thresholds for each boundary profile
    #   gain: list of boolean values indicating whether the criterion is gain or cost
    # Returns:
    #   marginal_concordance: numpy array with marginal concordance in the shape of (number of criteria, number of alternatives, number of boundary profiles)

    marginal_concordance_alt_to_profile = np.zeros((len(boundary_profiles),len(alternatives),len(alternatives.columns),))
    marginal_concordance_profile_to_alt = np.zeros((len(boundary_profiles),len(alternatives),len(alternatives.columns),))

    for i in range(len(alternatives)):
        for j in range(len(boundary_profiles)):
            for k in range(len(alternatives.columns)):
                difference = alternatives.iloc[i,k] - boundary_profiles.iloc[j,k]
                
                indifference = indifference_thresholds[j][k]
                preference = preference_thresholds[j][k]
                marginal_concordance_alt_to_profile[j,i,k] = concordance_function(difference, indifference, preference, gain[k])
                marginal_concordance_profile_to_alt[j,i,k] = concordance_function(-difference, indifference, preference, gain[k])

    return marginal_concordance_alt_to_profile,marginal_concordance_profile_to_alt

def test_marginal_concordance():

    
    test_alternatives = pd.DataFrame([[90,86,46,30],
    [40,90,14,48],
    [94,100,40,36],
    [78,76,30,50],
    [60,60,30,30],
    [64,72,12,46],
    [62,88,22,48],
    [70,30,12,12]]).astype(float)
    test_boundary_profiles = pd.DataFrame( [[64,61,32,32],
[86,84,43,43]]).astype(float)
    test_indifference_thresholds = [[2,2,0,0],[3,2,0,0]]
    test_preference_thresholds = [[6,5,2,2],[7,8,2,2]]

    test_gains = [True,True,True,True]

    marginal_concordance_alt_to_profile, marginal_concordance_profile_to_alt = calculate_marginal_concordance(test_alternatives, test_boundary_profiles, test_indifference_thresholds, test_preference_thresholds, test_gains)

    concordance_matrix_alt_to_profile = np.array(
        [
        [1,1,1,0],
        [0,1,0,1],
        [1,1,1,1],
        [1,1,0,1],
        [0.5,1,0,0],
        [1,1,0,1],
        [1,1,0,1],
        [1,0,0,0]
        ],
    )
    concordance_matrix_profile_to_alt = np.array(
        [
        [0,0,0,1],
        [1,0,1,0],
        [0,0,0,0],
        [0,0,1,0],
        [1,1,1,1],
        [1,0,1,0],
        [1,0,1,0],
        [0,1,1,1]
        ]
    )
    assert np.allclose(marginal_concordance_alt_to_profile[0], concordance_matrix_alt_to_profile, atol=0.01)
    assert np.allclose(marginal_concordance_profile_to_alt[0], concordance_matrix_profile_to_alt, atol=0.01)

    return marginal_concordance_alt_to_profile, marginal_concordance_profile_to_alt

test_marginal_concordance()

(array([[[1. , 1. , 1. , 0. ],
         [0. , 1. , 0. , 1. ],
         [1. , 1. , 1. , 1. ],
         [1. , 1. , 0. , 1. ],
         [0.5, 1. , 0. , 0. ],
         [1. , 1. , 0. , 1. ],
         [1. , 1. , 0. , 1. ],
         [1. , 0. , 0. , 0. ]],
 
        [[1. , 1. , 1. , 0. ],
         [0. , 1. , 0. , 1. ],
         [1. , 1. , 0. , 0. ],
         [0. , 0. , 0. , 1. ],
         [0. , 0. , 0. , 0. ],
         [0. , 0. , 0. , 1. ],
         [0. , 1. , 0. , 1. ],
         [0. , 0. , 0. , 0. ]]]),
 array([[[0.        , 0.        , 0.        , 1.        ],
         [1.        , 0.        , 1.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 1.        , 0.        ],
         [1.        , 1.        , 1.        , 1.        ],
         [1.        , 0.        , 1.        , 0.        ],
         [1.        , 0.        , 1.        , 0.        ],
         [0.        , 1.        , 1.        , 1.        ]],
 
        [[0.75      , 1

In [64]:
def discordance_function(difference, veto, preference, gain):
    if gain:
        if difference <= -veto:
            return 1
        elif difference >= -preference:
            return 0
        else :
            return (-difference - preference) / (veto-preference)
    else:
        if difference >= veto:
            return 1
        elif difference <= preference:
            return 0
        else:
            return (veto - difference) / (veto-preference)

def calculate_marginal_discordance(alternatives,boundary_profiles,preference_thresholds,veto_thresholds,gain,discordance_function=discordance_function):

    marginal_discordance_alt_to_profile = np.zeros((len(boundary_profiles),len(alternatives),len(alternatives.columns),))
    marginal_discordance_profile_to_alt = np.zeros((len(boundary_profiles),len(alternatives),len(alternatives.columns),))

    for i in range(len(alternatives)):
        for j in range(len(boundary_profiles)):
            for k in range(len(alternatives.columns)):
                difference = alternatives.iloc[i,k] - boundary_profiles.iloc[j,k]
                
                veto = veto_thresholds[j][k]
                preference = preference_thresholds[j][k]
                marginal_discordance_alt_to_profile[j,i,k] = discordance_function(difference, veto, preference, gain[k])
                marginal_discordance_profile_to_alt[j,i,k] = discordance_function(-difference, veto, preference, gain[k])

    return marginal_discordance_alt_to_profile,marginal_discordance_profile_to_alt

def test_marginal_discordance():

    test_alternatives = pd.DataFrame([[90,86,46,30],
    [40,90,14,48],
    [94,100,40,36],
    [78,76,30,50],
    [60,60,30,30],
    [64,72,12,46],
    [62,88,22,48],
    [70,30,12,12]]).astype(float)
    test_boundary_profiles = pd.DataFrame( [[64,61,32,32],
[86,84,43,43]]).astype(float)
    test_veto_thresholds = [[20,24,np.inf,np.inf],[20,25,np.inf,np.inf]]
    test_preference_thresholds = [[6,5,2,2],[7,8,2,2]]

    test_gains = [True,True,True,True]

    discordance_alt_to_profile = np.array([
        [0,0,0,0],
        [1,0,0,0],
        [0,0,0,0],
        [0.07,0,0,0],
        [1,0.94,0,0],
        [1,0.23,0,0],
        [1,0,0,0],
        [0.69,1,0,0]
    ])
    discordance_profile_to_alt = np.array([
        [1,1,0,0],
        [0,1,0,0],
        [1,1,0,0],
        [0.57,0.52,0,0],
        [0,0,0,0],
        [0,0.31,0,0],
        [0,1,0,0],
        [0,0,0,0]
    ])

    marginal_discordance_alt_to_profile, marginal_discordance_profile_to_alt = calculate_marginal_discordance(test_alternatives, test_boundary_profiles, test_preference_thresholds, test_veto_thresholds,test_gains)

    assert np.allclose(marginal_discordance_alt_to_profile[1], discordance_alt_to_profile, atol=0.01)
    assert np.allclose(marginal_discordance_profile_to_alt[0], discordance_profile_to_alt, atol=0.01)

    return marginal_discordance_alt_to_profile, marginal_discordance_profile_to_alt
    
test_marginal_discordance()

(array([[[0.        , 0.        , 0.        , 0.        ],
         [1.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.        , 1.        , 0.        , 0.        ]],
 
        [[0.        , 0.        , 0.        , 0.        ],
         [1.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
         [0.07692308, 0.        , 0.        , 0.        ],
         [1.        , 0.94117647, 0.        , 0.        ],
         [1.        , 0.23529412, 0.        , 0.        ],
         [1.        , 0.        , 0.        , 0.        ],
         [0.69230769, 1.        , 0.        , 0.        ]]]),
 array([[[1.        , 1.        , 0.        , 0.  

In [76]:
def calculate_comprehensive_concordance(concordance_matrix_alt_to_profile, concordance_matrix_profile_to_alt,weights):

    # weighted average of concordances for each alternative

    comprehensive_concordance_alt_to_profile = np.average(concordance_matrix_alt_to_profile, axis=2, weights=weights)
    comprehensive_concordance_profile_to_alt = np.average(concordance_matrix_profile_to_alt, axis=2, weights=weights)

    return comprehensive_concordance_alt_to_profile.T, comprehensive_concordance_profile_to_alt.T

def test_comprehensive_concordance():

    concordance_matrix_alt_to_profile, concordance_matrix_profile_to_alt = test_marginal_concordance()

    weights = [0.4,0.3,0.25,0.05]

    comprehensive_concordance_alt_to_profile, comprehensive_concordance_profile_to_alt = calculate_comprehensive_concordance(concordance_matrix_alt_to_profile, concordance_matrix_profile_to_alt,weights)
    return comprehensive_concordance_alt_to_profile, comprehensive_concordance_profile_to_alt

test_comprehensive_concordance()

(array([[0.95, 0.95],
        [0.35, 0.35],
        [1.  , 0.7 ],
        [0.75, 0.05],
        [0.5 , 0.  ],
        [0.75, 0.05],
        [0.75, 0.35],
        [0.4 , 0.  ]]),
 array([[0.05, 0.65],
        [0.65, 0.75],
        [0.  , 0.3 ],
        [0.25, 0.95],
        [1.  , 1.  ],
        [0.65, 0.95],
        [0.65, 0.85],
        [0.6 , 1.  ]]))

In [102]:
def calculate_outranking_credibility(comprehensive_concordance,marginal_discordance):
    # Returns array of outranking credibility for each alternative
    # outranking[alternative][boundary profile][0] = outranking credibility of alternative to boundary profile
    # outranking[alternative][boundary profile][1] = outranking credibility of boundary profile to alternative
    outrankings = np.zeros((len(comprehensive_concordance[0]),len(comprehensive_concordance[0][0]),2))
    for i in range(len(comprehensive_concordance[0])): # numver of alternatives
        for j in range(len(comprehensive_concordance[0][0])): # number of boundary profiles
            outranking = [comprehensive_concordance[0][i][j], comprehensive_concordance[1][i][j]]
            for k in range(len(marginal_discordance[0])): # number of criteria
                
                if comprehensive_concordance[0][i][j] < marginal_discordance[0][j][i][k]: # alt_to_profile
                    outranking[0] *= (1-marginal_discordance[0][j][i][k])/(1-comprehensive_concordance[0][i][j])
                if comprehensive_concordance[1][i][j] < marginal_discordance[1][j][i][k]: # profile_to_alt
                    outranking[1] *= (1-marginal_discordance[1][j][i][k])/(1-comprehensive_concordance[1][i][j])
            outrankings[i][j] = outranking
    
    return outrankings

def test_outranking_credibility():

    comprehensive_concordance = test_comprehensive_concordance()
    marginal_discordance = test_marginal_discordance()

    outrankings = calculate_outranking_credibility(comprehensive_concordance,marginal_discordance)
    test_outrankings = np.array([[0.95,0],[0.95,0.65]])
    assert np.allclose(outrankings[0], test_outrankings, atol=0.01)
    return outrankings
test_outranking_credibility()

array([[[0.95      , 0.        ],
        [0.95      , 0.65      ]],

       [[0.        , 0.        ],
        [0.        , 0.75      ]],

       [[1.        , 0.        ],
        [0.7       , 0.22689076]],

       [[0.75      , 0.09022556],
        [0.048583  , 0.95      ]],

       [[0.5       , 1.        ],
        [0.        , 1.        ]],

       [[0.75      , 0.65      ],
        [0.        , 0.95      ]],

       [[0.75      , 0.        ],
        [0.        , 0.85      ]],

       [[0.        , 0.6       ],
        [0.        , 1.        ]]])

In [116]:
def preference_aggregation(aPb,bPa):
    if aPb and not bPa:
        return 1 # a is preferred to b
    if not aPb and bPa:
        return -1 # b is preferred to a
    if aPb and bPa: 
        return 0 # indifferent
    if not aPb and not bPa:
        return None # incomparable

def transform_outranking_to_preference(outrankings,credibility_threshold=0.65):

    outranking_preference = np.zeros((len(outrankings),len(outrankings[0])))
    for i in range(len(outrankings)): # alternatives
        for j in range(len(outrankings[0])): # boundary profiles
            outranking_preference[i][j] = preference_aggregation(outrankings[i][j][0] >= credibility_threshold, outrankings[i][j][1] >= credibility_threshold)
    return outranking_preference

def test_transform_outranking_to_preference():
    outrankings = test_outranking_credibility()
    outranking_preference = transform_outranking_to_preference(outrankings)
    assert np.allclose(outranking_preference[:,0:1].flatten(), [[1,np.nan,1,1,-1,0,1,np.nan]], equal_nan=True)
    return outranking_preference

preference = test_transform_outranking_to_preference()
print(preference[:,0:1])
print(preference[:,1:2])

[[ 1.]
 [nan]
 [ 1.]
 [ 1.]
 [-1.]
 [ 0.]
 [ 1.]
 [nan]]
[[ 0.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]


In [135]:
def class_assignment(preference_matrix, pessimistic=True):
    if pessimistic:
        # fill array of size len(preference_matrix) with max value of 2
        classes = np.full(len(preference_matrix),3)

    else:
        classes = np.ones(len(preference_matrix))


    for j,a in enumerate(preference_matrix):
        if pessimistic:
            for i in range(len(a)-1,-1,-1):
                
                if a[i] >=0:
                    break
                classes[j]-=1
            
        else:
            for i in range(len(a)):
                if a[i] == -1:
                    break
                classes[j]+=1
                
    return classes

def test_class_assignment():

    preference = test_transform_outranking_to_preference()
    classes_pess = class_assignment(preference,True)
    classes_opt = class_assignment(preference,False)
    assert np.allclose(classes_pess, [3,1,3,2,1,2,2,1])
    assert np.allclose(classes_opt, [3,2,3,2,1,2,2,2])
    return classes_pess, classes_opt

test_class_assignment()

(array([3, 1, 3, 2, 1, 2, 2, 1]), array([3., 2., 3., 2., 1., 2., 2., 2.]))

In [136]:
def electre_tri_b(alternatives,boundary_profiles,criteria_is_gain,indifference_thresholds,preference_thresholds,veto_thresholds,weights,pessimistic=True):
    # Returns array of classes for each alternative

    # Calculate concordance and discordance matrices
    concordance_matrix_alt_to_profile, concordance_matrix_profile_to_alt = calculate_marginal_concordance(alternatives,boundary_profiles,indifference_thresholds,preference_thresholds,criteria_is_gain)
    discordance_matrix_alt_to_profile, discordance_matrix_profile_to_alt = calculate_marginal_discordance(alternatives,boundary_profiles,preference_thresholds,veto_thresholds,criteria_is_gain)

    # Calculate comprehensive concordance
    comprehensive_concordance = calculate_comprehensive_concordance(concordance_matrix_alt_to_profile,concordance_matrix_profile_to_alt,weights)

    # Calculate outranking credibility
    outrankings = calculate_outranking_credibility(comprehensive_concordance,[discordance_matrix_alt_to_profile,discordance_matrix_profile_to_alt])

    # Transform outranking credibility to preference
    outranking_preference = transform_outranking_to_preference(outrankings)

    # Assign classes
    classes = class_assignment(outranking_preference,pessimistic)

    
    return classes

def test_electre_tri_b():
    
    test_alternatives = pd.DataFrame([[90,86,46,30],
    [40,90,14,48],
    [94,100,40,36],
    [78,76,30,50],
    [60,60,30,30],
    [64,72,12,46],
    [62,88,22,48],
    [70,30,12,12]]).astype(float)
    test_boundary_profiles = pd.DataFrame( [[64,61,32,32],
[86,84,43,43]]).astype(float)
    test_veto_thresholds = [[20,24,np.inf,np.inf],[20,25,np.inf,np.inf]]
    test_preference_thresholds = [[6,5,2,2],[7,8,2,2]]
    test_indifference_thresholds = [[2,2,0,0],[3,2,0,0]]
    test_gains = [True,True,True,True]
    test_weights = [0.4,0.3,0.25,0.05]

    classes = electre_tri_b(test_alternatives,test_boundary_profiles,test_gains,test_indifference_thresholds,test_preference_thresholds,test_veto_thresholds,test_weights)
    assert np.allclose(classes, [3,1,3,2,1,2,2,1])
    return classes

test_electre_tri_b() 

array([3, 1, 3, 2, 1, 2, 2, 1])

## Evaluation on our data

In [141]:
alternatives = get_alternatives()
boundary_profiles = [[2500,35,5,45,0],[2400,45,6,30,1],[2100,50,8,15,3]] # TODO

######################### Price, Area, Aesthetics, Commutation, Gym number
# Todo - nie wiem jak zinterpretować gym_num bo 0 a 1 ma największą wartość a reszta to im więcej tym lepiej, tyle że te algorytmy działają na różnicach
INDIFFERENCE_THRESHOLDS = [[],[],[]] # I feel indifferent when the difference is X
PREFERENCE_THRESHOLDS = [[],[],[]] # I feel preference when the difference is X
VETO_THRESHOLDS = [[],[],[]] # A is always better than B if the difference is X and there is no question about that
gain = [False, True, True, False, True]

WEIGHTS = [0.51,0.28,0.16,0.16,0.05] # SRF

In [11]:
electre_tri_b()


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### COMPARISON